// <auto-generated />
using System;
using Articles.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Articles.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241130220952_ArticleSeed")]
    partial class ArticleSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Articles.Models.ArticleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "1 cooles Werkzeug",
                            ReleaseDate = new DateTime(2024, 11, 30, 23, 9, 52, 361, DateTimeKind.Local).AddTicks(7292),
                            Title = "Schraube"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Haut rein!",
                            ReleaseDate = new DateTime(2024, 11, 30, 23, 9, 52, 361, DateTimeKind.Local).AddTicks(7352),
                            Title = "Hammer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
